version: "3.8"

services:
  bootnode:
    image: ethereum/client-go:alltools-v1.13.1
    command:
      - bootnode
      - --nodekey=/tmp/boot.key
      - --addr=:30301
      - --verbosity=9
    volumes:
      - ./boot.key:/tmp/boot.key
    networks:
      suave:

  poasigner1:
    build: ../..
    command:
      - --chain=/genesis.json
      - --syncmode=full
      - --allow-insecure-unlock
      - --keystore=/keystore
      - --unlock=0x1967a08Ca1eE988062E47DbfDa429D9543a7799C
      - --password=/keystore/password.txt
      - --mine
      - --miner.etherbase=0x1967a08Ca1eE988062E47DbfDa429D9543a7799C
    volumes:
      - ./signer1/keystore:/keystore
      - ./genesis.json:/genesis.json
    networks:
      suave:
    depends_on:
      - bootnode

  poasigner2:
    build: ../..
    command:
      - --chain=/genesis.json
      - --syncmode=full
      - --allow-insecure-unlock
      - --keystore=/keystore
      - --unlock=0xE25EB0412BF1692f28287969CBAB084076F4Bb96
      - --password=/keystore/password.txt
      - --mine
      - --miner.etherbase=0xE25EB0412BF1692f28287969CBAB084076F4Bb96
    volumes:
      - ./signer2/keystore:/keystore
      - ./genesis.json:/genesis.json
    networks:
      suave:
    depends_on:
      - bootnode

  poasigner3:
    build: ../..
    command:
      - --chain=/genesis.json
      - --syncmode=full
      - --allow-insecure-unlock
      - --keystore=/keystore
      - --unlock=0x9AA51950F72a7dAA4d9E95585AD4f4d137e4BFDe
      - --password=/keystore/password.txt
      - --mine
      - --miner.etherbase=0x9AA51950F72a7dAA4d9E95585AD4f4d137e4BFDe
    volumes:
      - ./signer3/keystore:/keystore
      - ./genesis.json:/genesis.json
    networks:
      suave:
    depends_on:
      - bootnode

  mevm1:
    build: ../..
    command:
      - --chain=/genesis.json
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --keystore=/keystore/keystore
      - --unlock=0xB5fEAfbDD752ad52Afb7e1bD2E40432A485bBB7F
      - --password=/keystore/password.txt
    volumes:
      - ./suave-ex-node:/keystore
      - ./genesis.json:/genesis.json
    ports:
      - 8545:8545
    networks:
      suave:
    depends_on:
      - bootnode

networks:
  suave:
