version: "3.8"

services:
  suave:
    build: ../..
    command:
      - --suave
      - --http
      - --ws
      - --dev.gaslimit=30000000
      - --datadir=/data
      - --keystore=/keystore/keystore
      - --allow-insecure-unlock
      - --unlock=0xB5fEAfbDD752ad52Afb7e1bD2E40432A485bBB7F
      - --password=/keystore/password.txt
      - --mine
      - --miner.etherbase=0xB5fEAfbDD752ad52Afb7e1bD2E40432A485bBB7F
      - --suave.eth.remote_endpoint=suave-enabled-chain:8545
    volumes:
      - ./suave-chain:/keystore

  suave-enabled-chain:
    build: ../..
    command:
      - --dev
      - --http
      - --ws
      - --dev.gaslimit=30000000
      - --datadir=/data
      - --keystore=/keystore/keystore
      - --allow-insecure-unlock
      - --unlock=0xB5fEAfbDD752ad52Afb7e1bD2E40432A485bBB7F
      - --password=/keystore/password.txt
      - --mine
      - --miner.etherbase=0xB5fEAfbDD752ad52Afb7e1bD2E40432A485bBB7F
    volumes:
      - ./suave-enabled-chain:/keystore
